# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAngPDPCheckout():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_angPDPCheckout(self):
    self.driver.get("https://habit.pixalized.com/")
    self.driver.set_window_size(1382, 784)
    self.driver.find_element(By.ID, "search").click()
    self.driver.find_element(By.ID, "search").send_keys("QA1")
    self.driver.find_element(By.ID, "search").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".product_image").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-squared").click()
    self.driver.find_element(By.CSS_SELECTOR, ".aria-hidden").click()
    self.driver.find_element(By.CSS_SELECTOR, ".link-to-cart .mr-1").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".link-to-cart > .nav-link")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-sm:nth-child(1)").click()
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").send_keys("Belden")
    self.driver.find_element(By.CSS_SELECTOR, ".status-pab:nth-child(6) .checkbox").click()
    self.driver.find_element(By.CSS_SELECTOR, ".status-pab:nth-child(7) > .address_checkbox").click()
    self.driver.find_element(By.CSS_SELECTOR, ".status-pab:nth-child(7) > .address_checkbox").click()
    self.driver.find_element(By.CSS_SELECTOR, ".status-pab:nth-child(7) .checkbox").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-right > .btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".billing-breadcrumb-disabled > .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".text-right > .btn").click()
    self.driver.execute_script("window.scrollTo(0,585)")
    self.driver.find_element(By.CSS_SELECTOR, ".text-right > .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".payment-method-option:nth-child(1) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".co-payment-credit-card-row:nth-child(1) label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".section-order-sign-off").click()
    self.driver.find_element(By.CSS_SELECTOR, "label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
