# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# Configuration - Update these for your site/user
SITE_URL = "https://[SITENAME].pixalized.com/sign-in"
USERNAME = "your_email@gmail.com"
PASSWORD = "your_password"

class TestSSOLogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sSOLogin(self):
    self.driver.get(SITE_URL)
    self.driver.set_window_size(1382, 784)
    self.driver.find_element(By.LINK_TEXT, "click here to be directed to vendor login").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys(USERNAME)
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys(PASSWORD)
    self.driver.find_element(By.NAME, "commit").click()
